[package]
name = "parquet-rest"
version = "0.1.0"
authors = ["Tikhon Jelvis <tikhon@jelv.is>"]
edition = "2018"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
parquet = "1.0.1"